//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TDS.Averbacao.br.com.averba.webserver {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ATMWebSvrBinding", Namespace="urn:ATMWebSvr")]
    public partial class ATMWebSvr : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback averbaCTeOperationCompleted;
        
        private System.Threading.SendOrPostCallback averbaNFeOperationCompleted;
        
        private System.Threading.SendOrPostCallback declaraMDFeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddBackMailOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ATMWebSvr() {
            this.Url = global::TDS.Averbacao.Properties.Settings.Default.TDS_Averbacao_br_com_averba_webserver_ATMWebSvr;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event averbaCTeCompletedEventHandler averbaCTeCompleted;
        
        /// <remarks/>
        public event averbaNFeCompletedEventHandler averbaNFeCompleted;
        
        /// <remarks/>
        public event declaraMDFeCompletedEventHandler declaraMDFeCompleted;
        
        /// <remarks/>
        public event AddBackMailCompletedEventHandler AddBackMailCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ATMWebSvr#averbaCTe", RequestNamespace="urn:ATMWebSvr", ResponseNamespace="urn:ATMWebSvr", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("Response")]
        public Retorno averbaCTe(string usuario, string senha, string codatm, string xmlCTe) {
            object[] results = this.Invoke("averbaCTe", new object[] {
                        usuario,
                        senha,
                        codatm,
                        xmlCTe});
            return ((Retorno)(results[0]));
        }
        
        /// <remarks/>
        public void averbaCTeAsync(string usuario, string senha, string codatm, string xmlCTe) {
            this.averbaCTeAsync(usuario, senha, codatm, xmlCTe, null);
        }
        
        /// <remarks/>
        public void averbaCTeAsync(string usuario, string senha, string codatm, string xmlCTe, object userState) {
            if ((this.averbaCTeOperationCompleted == null)) {
                this.averbaCTeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaverbaCTeOperationCompleted);
            }
            this.InvokeAsync("averbaCTe", new object[] {
                        usuario,
                        senha,
                        codatm,
                        xmlCTe}, this.averbaCTeOperationCompleted, userState);
        }
        
        private void OnaverbaCTeOperationCompleted(object arg) {
            if ((this.averbaCTeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.averbaCTeCompleted(this, new averbaCTeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ATMWebSvr#averbaNFe", RequestNamespace="urn:ATMWebSvr", ResponseNamespace="urn:ATMWebSvr", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("Response")]
        public Retorno averbaNFe(string usuario, string senha, string codatm, string xmlNFe) {
            object[] results = this.Invoke("averbaNFe", new object[] {
                        usuario,
                        senha,
                        codatm,
                        xmlNFe});
            return ((Retorno)(results[0]));
        }
        
        /// <remarks/>
        public void averbaNFeAsync(string usuario, string senha, string codatm, string xmlNFe) {
            this.averbaNFeAsync(usuario, senha, codatm, xmlNFe, null);
        }
        
        /// <remarks/>
        public void averbaNFeAsync(string usuario, string senha, string codatm, string xmlNFe, object userState) {
            if ((this.averbaNFeOperationCompleted == null)) {
                this.averbaNFeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaverbaNFeOperationCompleted);
            }
            this.InvokeAsync("averbaNFe", new object[] {
                        usuario,
                        senha,
                        codatm,
                        xmlNFe}, this.averbaNFeOperationCompleted, userState);
        }
        
        private void OnaverbaNFeOperationCompleted(object arg) {
            if ((this.averbaNFeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.averbaNFeCompleted(this, new averbaNFeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ATMWebSvr#declaraMDFe", RequestNamespace="urn:ATMWebSvr", ResponseNamespace="urn:ATMWebSvr", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("Response")]
        public RetornoMDFe declaraMDFe(string usuario, string senha, string codatm, string xmlMDFe) {
            object[] results = this.Invoke("declaraMDFe", new object[] {
                        usuario,
                        senha,
                        codatm,
                        xmlMDFe});
            return ((RetornoMDFe)(results[0]));
        }
        
        /// <remarks/>
        public void declaraMDFeAsync(string usuario, string senha, string codatm, string xmlMDFe) {
            this.declaraMDFeAsync(usuario, senha, codatm, xmlMDFe, null);
        }
        
        /// <remarks/>
        public void declaraMDFeAsync(string usuario, string senha, string codatm, string xmlMDFe, object userState) {
            if ((this.declaraMDFeOperationCompleted == null)) {
                this.declaraMDFeOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeclaraMDFeOperationCompleted);
            }
            this.InvokeAsync("declaraMDFe", new object[] {
                        usuario,
                        senha,
                        codatm,
                        xmlMDFe}, this.declaraMDFeOperationCompleted, userState);
        }
        
        private void OndeclaraMDFeOperationCompleted(object arg) {
            if ((this.declaraMDFeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.declaraMDFeCompleted(this, new declaraMDFeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ATMWebSvr#AddBackMail", RequestNamespace="urn:ATMWebSvr", ResponseNamespace="urn:ATMWebSvr", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string AddBackMail(string usuario, string senha, string codatm, string aplicacao, string assunto, string remetentes, string destinatarios, string corpo, string chave, string chaveresp) {
            object[] results = this.Invoke("AddBackMail", new object[] {
                        usuario,
                        senha,
                        codatm,
                        aplicacao,
                        assunto,
                        remetentes,
                        destinatarios,
                        corpo,
                        chave,
                        chaveresp});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddBackMailAsync(string usuario, string senha, string codatm, string aplicacao, string assunto, string remetentes, string destinatarios, string corpo, string chave, string chaveresp) {
            this.AddBackMailAsync(usuario, senha, codatm, aplicacao, assunto, remetentes, destinatarios, corpo, chave, chaveresp, null);
        }
        
        /// <remarks/>
        public void AddBackMailAsync(string usuario, string senha, string codatm, string aplicacao, string assunto, string remetentes, string destinatarios, string corpo, string chave, string chaveresp, object userState) {
            if ((this.AddBackMailOperationCompleted == null)) {
                this.AddBackMailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddBackMailOperationCompleted);
            }
            this.InvokeAsync("AddBackMail", new object[] {
                        usuario,
                        senha,
                        codatm,
                        aplicacao,
                        assunto,
                        remetentes,
                        destinatarios,
                        corpo,
                        chave,
                        chaveresp}, this.AddBackMailOperationCompleted, userState);
        }
        
        private void OnAddBackMailOperationCompleted(object arg) {
            if ((this.AddBackMailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddBackMailCompleted(this, new AddBackMailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ATMWebSvr")]
    public partial class Retorno {
        
        private string numeroField;
        
        private string serieField;
        
        private string filialField;
        
        private string cNPJCliField;
        
        private string tpDocField;
        
        private string infAdicField;
        
        private ErroProcesso[] errosField;
        
        private SuccessProcesso averbadoField;
        
        private InfoProcesso[] infosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Filial {
            get {
                return this.filialField;
            }
            set {
                this.filialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CNPJCli {
            get {
                return this.cNPJCliField;
            }
            set {
                this.cNPJCliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string TpDoc {
            get {
                return this.tpDocField;
            }
            set {
                this.tpDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InfAdic {
            get {
                return this.infAdicField;
            }
            set {
                this.infAdicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Erro", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ErroProcesso[] Erros {
            get {
                return this.errosField;
            }
            set {
                this.errosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SuccessProcesso Averbado {
            get {
                return this.averbadoField;
            }
            set {
                this.averbadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Info", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public InfoProcesso[] Infos {
            get {
                return this.infosField;
            }
            set {
                this.infosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ATMWebSvr")]
    public partial class ErroProcesso {
        
        private string codigoField;
        
        private string descricaoField;
        
        private string valorEsperadoField;
        
        private string valorInformadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ValorEsperado {
            get {
                return this.valorEsperadoField;
            }
            set {
                this.valorEsperadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ValorInformado {
            get {
                return this.valorInformadoField;
            }
            set {
                this.valorInformadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ATMWebSvr")]
    public partial class SuccessProcessoMDFe {
        
        private System.DateTime dhChancelaField;
        
        private string protocoloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime dhChancela {
            get {
                return this.dhChancelaField;
            }
            set {
                this.dhChancelaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Protocolo {
            get {
                return this.protocoloField;
            }
            set {
                this.protocoloField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ATMWebSvr")]
    public partial class RetornoMDFe {
        
        private string numeroField;
        
        private string serieField;
        
        private string filialField;
        
        private ErroProcesso[] errosField;
        
        private SuccessProcessoMDFe declaradoField;
        
        private InfoProcesso[] infosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Filial {
            get {
                return this.filialField;
            }
            set {
                this.filialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Erro", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ErroProcesso[] Erros {
            get {
                return this.errosField;
            }
            set {
                this.errosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SuccessProcessoMDFe Declarado {
            get {
                return this.declaradoField;
            }
            set {
                this.declaradoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Info", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public InfoProcesso[] Infos {
            get {
                return this.infosField;
            }
            set {
                this.infosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ATMWebSvr")]
    public partial class InfoProcesso {
        
        private string codigoField;
        
        private string descricaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ATMWebSvr")]
    public partial class DadosSeguro {
        
        private string numeroAverbacaoField;
        
        private string cNPJSeguradoraField;
        
        private string nomeSeguradoraField;
        
        private string numApoliceField;
        
        private string tpMovField;
        
        private string tpDDRField;
        
        private string valorAverbadoField;
        
        private string ramoAverbadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NumeroAverbacao {
            get {
                return this.numeroAverbacaoField;
            }
            set {
                this.numeroAverbacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CNPJSeguradora {
            get {
                return this.cNPJSeguradoraField;
            }
            set {
                this.cNPJSeguradoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NomeSeguradora {
            get {
                return this.nomeSeguradoraField;
            }
            set {
                this.nomeSeguradoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NumApolice {
            get {
                return this.numApoliceField;
            }
            set {
                this.numApoliceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TpMov {
            get {
                return this.tpMovField;
            }
            set {
                this.tpMovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TpDDR {
            get {
                return this.tpDDRField;
            }
            set {
                this.tpDDRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ValorAverbado {
            get {
                return this.valorAverbadoField;
            }
            set {
                this.valorAverbadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RamoAverbado {
            get {
                return this.ramoAverbadoField;
            }
            set {
                this.ramoAverbadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ATMWebSvr")]
    public partial class SuccessProcesso {
        
        private System.DateTime dhAverbacaoField;
        
        private string protocoloField;
        
        private DadosSeguro[] dadosSeguroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime dhAverbacao {
            get {
                return this.dhAverbacaoField;
            }
            set {
                this.dhAverbacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Protocolo {
            get {
                return this.protocoloField;
            }
            set {
                this.protocoloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DadosSeguro", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DadosSeguro[] DadosSeguro {
            get {
                return this.dadosSeguroField;
            }
            set {
                this.dadosSeguroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void averbaCTeCompletedEventHandler(object sender, averbaCTeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class averbaCTeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal averbaCTeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Retorno Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Retorno)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void averbaNFeCompletedEventHandler(object sender, averbaNFeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class averbaNFeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal averbaNFeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Retorno Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Retorno)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void declaraMDFeCompletedEventHandler(object sender, declaraMDFeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class declaraMDFeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal declaraMDFeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetornoMDFe Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetornoMDFe)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void AddBackMailCompletedEventHandler(object sender, AddBackMailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddBackMailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddBackMailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591